"""G4beamline <-> openPMD/ParticleGroup adapters for the converter stage: BLTrackFile ASCII IO
(via pandas) and conversion to/from `pmd_beamphysics.ParticleGroup`. See docs/converter.md.
"""

import numpy as np
import pandas as pd

from sim.helpers.tools import MC2_EV

BLTRACK_COLUMNS = ["x", "y", "z", "Px", "Py", "Pz", "t",
                   "PDGid", "EventID", "TrackID", "ParentID", "Weight"]
_INT_COLS = ["PDGid", "EventID", "TrackID", "ParentID"]
PDG_ELECTRON = 11
PDG_POSITRON = -11
PDG_GAMMA = 22

_MEV_PER_EV = 1e-6
_MM_PER_M = 1e3
_NS_PER_S = 1e9
_M_E_MEV = MC2_EV * _MEV_PER_EV   # electron/positron rest mass [MeV/c^2]


def read_bltrackfile(path, pdgid=None):
    """Read a G4beamline BLTrackFile ASCII into a DataFrame (file units mm/MeV/c/ns).

    g4bl prefixes the data with `#`-comment header lines; `comment="#"` drops them and the fixed
    column order is supplied explicitly. `pdgid` (int or iterable) optionally keeps only those
    species. Integer columns are int64.
    """
    df = pd.read_csv(path, sep=r"\s+", comment="#", header=None, names=BLTRACK_COLUMNS)
    for c in _INT_COLS:
        df[c] = df[c].astype(np.int64)
    if pdgid is not None:
        df = df[np.isin(df["PDGid"].values, np.atleast_1d(pdgid))].reset_index(drop=True)
    return df


def write_bltrackfile(df, path, comment="generated by sim/helpers/g4bl.py"):
    """Write a DataFrame (BLTRACK_COLUMNS, file units) as a BLTrackFile g4bl `beam ascii` reads.

    Emits the canonical 3-line `#` header (provenance + column + unit lines, all comments g4bl
    skips on read) then space-separated rows; id columns are int so PDGid stays `11`, not `11.0`.
    """
    out = df[BLTRACK_COLUMNS].copy()
    for c in _INT_COLS:
        out[c] = out[c].astype(np.int64)
    header = (f"#BLTrackFile {comment}\n"
              "#x y z Px Py Pz t PDGid EventID TrackID ParentID Weight\n"
              "#mm mm mm MeV/c MeV/c MeV/c ns - - - - -\n")
    with open(path, "w") as fh:
        fh.write(header)
        out.to_csv(fh, sep=" ", index=False, header=False, float_format="%.10g")
    return path


def particlegroup_to_bltrack_df(pg, pdgid=PDG_ELECTRON, event_ids=None):
    """ParticleGroup (m, eV/c, s) -> BLTrackFile DataFrame (mm, MeV/c, ns), one row per macro.

    PDGid is set to `pdgid` for every row; EventID = `event_ids` (else 1..N -- the incident-particle
    identity); TrackID=1, ParentID=0, Weight=1 (g4bl Weight is a multiplicity, not the charge --
    physical charge bookkeeping lives in the driver).
    """
    n = pg.n_particle
    if event_ids is None:
        event_ids = np.arange(1, n + 1, dtype=np.int64)
    return pd.DataFrame({
        "x": np.asarray(pg.x) * _MM_PER_M,
        "y": np.asarray(pg.y) * _MM_PER_M,
        "z": np.asarray(pg.z) * _MM_PER_M,
        "Px": np.asarray(pg.px) * _MEV_PER_EV,
        "Py": np.asarray(pg.py) * _MEV_PER_EV,
        "Pz": np.asarray(pg.pz) * _MEV_PER_EV,
        "t": np.asarray(pg.t) * _NS_PER_S,
        "PDGid": np.full(n, pdgid, dtype=np.int64),
        "EventID": np.asarray(event_ids, dtype=np.int64),
        "TrackID": np.ones(n, dtype=np.int64),
        "ParentID": np.zeros(n, dtype=np.int64),
        "Weight": np.ones(n),
    })


def bltrack_df_to_particlegroup(df, species, weight_C):
    """BLTrackFile DataFrame (mm, MeV/c, ns) -> ParticleGroup (m, eV/c, s).

    `species` is the ParticleGroup spelling ("positron"/"electron"); `weight_C` is the per-row charge
    magnitude [C] (scalar or array). ParticleGroup derives the signed charge/mass from `species`.
    """
    from pmd_beamphysics import ParticleGroup
    n = len(df)
    weight_C = np.broadcast_to(np.asarray(weight_C, dtype=float), (n,)).copy()
    return ParticleGroup(data=dict(
        x=df["x"].values / _MM_PER_M,
        y=df["y"].values / _MM_PER_M,
        z=df["z"].values / _MM_PER_M,
        px=df["Px"].values / _MEV_PER_EV,
        py=df["Py"].values / _MEV_PER_EV,
        pz=df["Pz"].values / _MEV_PER_EV,
        t=df["t"].values / _NS_PER_S,
        weight=weight_C,
        status=np.ones(n, dtype=np.int64), species=species))


def bltrack_ke_mev(df):
    """Kinetic energy [MeV] per row from the BLTrackFile momenta (electron/positron rest mass)."""
    p = np.sqrt(df["Px"].values ** 2 + df["Py"].values ** 2 + df["Pz"].values ** 2)   # MeV/c
    return np.sqrt(p * p + _M_E_MEV * _M_E_MEV) - _M_E_MEV
